package cm.beni.main.julia.model.schema.navires;
// Generated 2 ao�t 2020 02:42:51 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.voodoodyne.jackson.jsog.JSOGGenerator;

import cm.beni.main.julia.dao.controller.ObjectIdResolver;
import cm.beni.main.julia.model.schema.dossiers.Dossier;

/**
 * DossierNavires generated by hbm2java
 */
@Entity
@Table(name = "dossier_navires", schema = "navires")
//@JsonIdentityInfo(generator=ObjectIdGenerators.UUIDGenerator.class, property="@dossierNavires", scope = DossierNavires.class, resolver = ObjectIdResolver.class)
@JsonIdentityInfo(generator=JSOGGenerator.class, resolver = ObjectIdResolver.class)
public class DossierNavires implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String identify;
	private Navire navire;
	private Dossier dossier;

	public DossierNavires() {
	}

	public DossierNavires(String identify, Navire navire, Dossier dossier) {
		this.identify = identify;
		this.navire = navire;
		this.dossier = dossier;
	}

	@Id

	@Column(name = "identify", unique = true, nullable = false, length = 64)
	public String getIdentify() {
		return this.identify;
	}

	public void setIdentify(String identify) {
		this.identify = identify;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "navire", nullable = false)
	public Navire getNavire() {
		return this.navire;
	}

	public void setNavire(Navire navire) {
		this.navire = navire;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dossier", nullable = false)
	public Dossier getDossier() {
		return this.dossier;
	}

	public void setDossier(Dossier dossier) {
		this.dossier = dossier;
	}

}
