package cm.beni.main.julia.model.schema.navires;
// Generated 2 ao�t 2020 02:42:51 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import cm.beni.main.julia.dao.controller.ObjectIdResolver;

/**
 * Navire generated by hbm2java
 */
@Entity
@Table(name = "navire", schema = "navires", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
@JsonIdentityInfo(generator=ObjectIdGenerators.UUIDGenerator.class, property="@navire", scope = Navire.class, resolver = ObjectIdResolver.class)
public class Navire implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String identify;
	private String code;
	private String libelle;
	private Set<DossierNavires> dossierNavireses = new HashSet<DossierNavires>(0);

	public Navire() {
	}

	public Navire(String identify, String code, String libelle) {
		this.identify = identify;
		this.code = code;
		this.libelle = libelle;
	}

	public Navire(String identify, String code, String libelle, Set<DossierNavires> dossierNavireses) {
		this.identify = identify;
		this.code = code;
		this.libelle = libelle;
		this.dossierNavireses = dossierNavireses;
	}

	@Id

	@Column(name = "identify", unique = true, nullable = false, length = 64)
	public String getIdentify() {
		return this.identify;
	}

	public void setIdentify(String identify) {
		this.identify = identify;
	}

	@Column(name = "code", unique = true, nullable = false, length = 100)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "[libelle]", nullable = false, length = 200)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "navire")
	public Set<DossierNavires> getDossierNavireses() {
		return this.dossierNavireses;
	}

	public void setDossierNavireses(Set<DossierNavires> dossierNavireses) {
		this.dossierNavireses = dossierNavireses;
	}

}
