package cm.beni.main.julia.model.schema.access;
// Generated 2 ao�t 2020 02:32:19 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import cm.beni.main.julia.dao.controller.ObjectIdResolver;

/**
 * Authorization generated by hbm2java
 */
@Entity
@Table(name = "authorization", schema = "access", uniqueConstraints = @UniqueConstraint(columnNames = { "user",
		"widget" }))
@JsonIdentityInfo(generator=ObjectIdGenerators.UUIDGenerator.class, property="@authorization", scope = Authorization.class, resolver = ObjectIdResolver.class)
public class Authorization implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String identify;
	private String index;
	private String user;
	private String widget;
	private boolean visible;
	private boolean enable;

	public Authorization() {
	}

	public Authorization(String identify, String index, String user, String widget, boolean visible, boolean enable) {
		this.identify = identify;
		this.index = index;
		this.user = user;
		this.widget = widget;
		this.visible = visible;
		this.enable = enable;
	}

	@Id

	@Column(name = "identify", unique = true, nullable = false, length = 64)
	public String getIdentify() {
		return this.identify;
	}

	public void setIdentify(String identify) {
		this.identify = identify;
	}

	@Column(name = "index", nullable = false, length = 100)
	public String getIndex() {
		return this.index;
	}

	public void setIndex(String index) {
		this.index = index;
	}

	@Column(name = "user", nullable = false, length = 64)
	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	@Column(name = "widget", nullable = false, length = 64)
	public String getWidget() {
		return this.widget;
	}

	public void setWidget(String widget) {
		this.widget = widget;
	}

	@Column(name = "visible", nullable = false)
	public boolean isVisible() {
		return this.visible;
	}

	public void setVisible(boolean visible) {
		this.visible = visible;
	}

	@Column(name = "enable", nullable = false)
	public boolean isEnable() {
		return this.enable;
	}

	public void setEnable(boolean enable) {
		this.enable = enable;
	}

}
