package cm.beni.main.julia.model.schema.monitoring;
// Generated 2 ao�t 2020 02:40:42 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.voodoodyne.jackson.jsog.JSOGGenerator;

import cm.beni.main.julia.dao.controller.ObjectIdResolver;

/**
 * Monitor generated by hbm2java
 */
@Entity
@Table(name = "monitor", schema = "monitoring")
//@JsonIdentityInfo(generator=ObjectIdGenerators.UUIDGenerator.class, property="@monitor", scope = Monitor.class, resolver = ObjectIdResolver.class)
@JsonIdentityInfo(generator=JSOGGenerator.class, resolver = ObjectIdResolver.class)
public class Monitor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String identify;
	private Session session;
	private Date dateReelle;
	private String action;
	private String valeur;
	private String widget;
	private String status;
	private Set<Log> logs = new HashSet<Log>(0);

	public Monitor() {
	}

	public Monitor(String identify, Date dateReelle) {
		this.identify = identify;
		this.dateReelle = dateReelle;
	}

	public Monitor(String identify, Session session, Date dateReelle, String action, String valeur, String widget,
			String status, Set<Log> logs) {
		this.identify = identify;
		this.session = session;
		this.dateReelle = dateReelle;
		this.action = action;
		this.valeur = valeur;
		this.widget = widget;
		this.status = status;
		this.logs = logs;
	}

	@Id

	@Column(name = "identify", unique = true, nullable = false, length = 64)
	public String getIdentify() {
		return this.identify;
	}

	public void setIdentify(String identify) {
		this.identify = identify;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "session")
	public Session getSession() {
		return this.session;
	}

	public void setSession(Session session) {
		this.session = session;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_reelle", nullable = false, length = 13)
	public Date getDateReelle() {
		return this.dateReelle;
	}

	public void setDateReelle(Date dateReelle) {
		this.dateReelle = dateReelle;
	}

	@Column(name = "action", length = 200)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Column(name = "valeur", length = 200)
	public String getValeur() {
		return this.valeur;
	}

	public void setValeur(String valeur) {
		this.valeur = valeur;
	}

	@Column(name = "widget", length = 64)
	public String getWidget() {
		return this.widget;
	}

	public void setWidget(String widget) {
		this.widget = widget;
	}

	@Column(name = "status", length = 100)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "monitor")
	public Set<Log> getLogs() {
		return this.logs;
	}

	public void setLogs(Set<Log> logs) {
		this.logs = logs;
	}

}
