package cm.beni.main.julia.model.schema.monitoring;
// Generated 2 ao�t 2020 02:40:42 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.voodoodyne.jackson.jsog.JSOGGenerator;

import cm.beni.main.julia.dao.controller.ObjectIdResolver;

/**
 * Session generated by hbm2java
 */
@Entity
@Table(name = "session", schema = "monitoring")
//@JsonIdentityInfo(generator=ObjectIdGenerators.UUIDGenerator.class, property="@session", scope = Session.class, resolver = ObjectIdResolver.class)
@JsonIdentityInfo(generator=JSOGGenerator.class, resolver = ObjectIdResolver.class)
public class Session implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String identify;
	private String userRole;
	private String status;
	private Date dateConnected;
	private Date dataDisconnected;
	private Set<Monitor> monitors = new HashSet<Monitor>(0);

	public Session() {
	}

	public Session(String identify, String userRole, String status, Date dateConnected) {
		this.identify = identify;
		this.userRole = userRole;
		this.status = status;
		this.dateConnected = dateConnected;
	}

	public Session(String identify, String userRole, String status, Date dateConnected, Date dataDisconnected,
			Set<Monitor> monitors) {
		this.identify = identify;
		this.userRole = userRole;
		this.status = status;
		this.dateConnected = dateConnected;
		this.dataDisconnected = dataDisconnected;
		this.monitors = monitors;
	}

	@Id

	@Column(name = "identify", unique = true, nullable = false)
	public String getIdentify() {
		return this.identify;
	}

	public void setIdentify(String identify) {
		this.identify = identify;
	}

	@Column(name = "user_role", nullable = false, length = 64)
	public String getUserRole() {
		return this.userRole;
	}

	public void setUserRole(String userRole) {
		this.userRole = userRole;
	}

	@Column(name = "status", nullable = false, length = 100)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_connected", nullable = false, length = 13)
	public Date getDateConnected() {
		return this.dateConnected;
	}

	public void setDateConnected(Date dateConnected) {
		this.dateConnected = dateConnected;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_disconnected", length = 13)
	public Date getDataDisconnected() {
		return this.dataDisconnected;
	}

	public void setDataDisconnected(Date dataDisconnected) {
		this.dataDisconnected = dataDisconnected;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "session")
	public Set<Monitor> getMonitors() {
		return this.monitors;
	}

	public void setMonitors(Set<Monitor> monitors) {
		this.monitors = monitors;
	}

}
