package cm.beni.main.julia.model.schema.dossiers;
// Generated 2 ao�t 2020 02:34:56 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "client", schema = "dossiers", uniqueConstraints = @UniqueConstraint(columnNames = "personnal"))
//@JsonIdentityInfo(generator=ObjectIdGenerators.UUIDGenerator.class, property="@client", scope = Client.class, resolver = ObjectIdResolver.class)
public class Client implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String identify;
	private Personnal personnal;
	private String raisonSociale;
	private String adresse;
	private String numeroRc;
	private String nature;
	private Set<Dossier> dossiers = new HashSet<Dossier>(0);

	public Client() {
	}

	public Client(String identify, Personnal personnal) {
		this.identify = identify;
		this.personnal = personnal;
	}

	public Client(String identify, Personnal personnal, String raisonSociale, String adresse, String numeroRc,
			String nature, Set<Dossier> dossiers) {
		this.identify = identify;
		this.personnal = personnal;
		this.raisonSociale = raisonSociale;
		this.adresse = adresse;
		this.numeroRc = numeroRc;
		this.nature = nature;
		this.dossiers = dossiers;
	}

	@Id

	@Column(name = "identify", unique = true, nullable = false, length = 64)
	public String getIdentify() {
		return this.identify;
	}

	public void setIdentify(String identify) {
		this.identify = identify;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "personnal", unique = true, nullable = false)
	public Personnal getPersonnal() {
		return this.personnal;
	}

	public void setPersonnal(Personnal personnal) {
		this.personnal = personnal;
	}

	@Column(name = "raison_sociale", length = 200)
	public String getRaisonSociale() {
		return this.raisonSociale;
	}

	public void setRaisonSociale(String raisonSociale) {
		this.raisonSociale = raisonSociale;
	}

	@Column(name = "adresse")
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "numero_rc", length = 100)
	public String getNumeroRc() {
		return this.numeroRc;
	}

	public void setNumeroRc(String numeroRc) {
		this.numeroRc = numeroRc;
	}

	@Column(name = "nature", length = 200)
	public String getNature() {
		return this.nature;
	}

	public void setNature(String nature) {
		this.nature = nature;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
	public Set<Dossier> getDossiers() {
		return this.dossiers;
	}

	public void setDossiers(Set<Dossier> dossiers) {
		this.dossiers = dossiers;
	}

}
