package cm.beni.main.julia.model.schema.dossiers;
// Generated 2 ao�t 2020 02:34:56 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Dossier generated by hbm2java
 */
@Entity
@Table(name = "dossier", schema = "dossiers", uniqueConstraints = @UniqueConstraint(columnNames = "numero_dossier"))
//@JsonIdentityInfo(generator=ObjectIdGenerators.UUIDGenerator.class, property="@dossier", scope = Dossier.class, resolver = ObjectIdResolver.class)
public class Dossier implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String identify;
	private Client client;
	private Personnal personnalByExpediteur;
	private Personnal personnalByDestinataire;
	private String numeroDossier;
	private Date dateMiseEnPlace;
	private String repertoire;
	private String category;
	private String numeroTarifaire;
	private Double montantDeclare;
	private String bureau;
	private String regime;
	private Integer numeroDeclaration;
	private Date dateDeclaration;
	private Double montantTaxe;
	private String observation;

	public Dossier() {
	}

	public Dossier(String identify, Client client, String numeroDossier, Date dateMiseEnPlace) {
		this.identify = identify;
		this.client = client;
		this.numeroDossier = numeroDossier;
		this.dateMiseEnPlace = dateMiseEnPlace;
	}

	public Dossier(String identify, Client client, Personnal personnalByExpediteur, Personnal personnalByDestinataire,
			String numeroDossier, Date dateMiseEnPlace, String repertoire, String category, String numeroTarifaire,
			Double montantDeclare, String bureau, String regime, Integer numeroDeclaration, Date dateDeclaration,
			Double montantTaxe, String observation) {
		this.identify = identify;
		this.client = client;
		this.personnalByExpediteur = personnalByExpediteur;
		this.personnalByDestinataire = personnalByDestinataire;
		this.numeroDossier = numeroDossier;
		this.dateMiseEnPlace = dateMiseEnPlace;
		this.repertoire = repertoire;
		this.category = category;
		this.numeroTarifaire = numeroTarifaire;
		this.montantDeclare = montantDeclare;
		this.bureau = bureau;
		this.regime = regime;
		this.numeroDeclaration = numeroDeclaration;
		this.dateDeclaration = dateDeclaration;
		this.montantTaxe = montantTaxe;
		this.observation = observation;
	}

	@Id

	@Column(name = "identify", unique = true, nullable = false, length = 64)
	public String getIdentify() {
		return this.identify;
	}

	public void setIdentify(String identify) {
		this.identify = identify;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "client", nullable = false)
	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "expediteur")
	public Personnal getPersonnalByExpediteur() {
		return this.personnalByExpediteur;
	}

	public void setPersonnalByExpediteur(Personnal personnalByExpediteur) {
		this.personnalByExpediteur = personnalByExpediteur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "destinataire")
	public Personnal getPersonnalByDestinataire() {
		return this.personnalByDestinataire;
	}

	public void setPersonnalByDestinataire(Personnal personnalByDestinataire) {
		this.personnalByDestinataire = personnalByDestinataire;
	}

	@Column(name = "numero_dossier", unique = true, nullable = false, length = 100)
	public String getNumeroDossier() {
		return this.numeroDossier;
	}

	public void setNumeroDossier(String numeroDossier) {
		this.numeroDossier = numeroDossier;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_mise_en_place", nullable = false, length = 13)
	public Date getDateMiseEnPlace() {
		return this.dateMiseEnPlace;
	}

	public void setDateMiseEnPlace(Date dateMiseEnPlace) {
		this.dateMiseEnPlace = dateMiseEnPlace;
	}

	@Column(name = "repertoire", length = 64)
	public String getRepertoire() {
		return this.repertoire;
	}

	public void setRepertoire(String repertoire) {
		this.repertoire = repertoire;
	}

	@Column(name = "category", length = 100)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "numero_tarifaire", length = 100)
	public String getNumeroTarifaire() {
		return this.numeroTarifaire;
	}

	public void setNumeroTarifaire(String numeroTarifaire) {
		this.numeroTarifaire = numeroTarifaire;
	}

	@Column(name = "montant_declare", scale = 0)
	public Double getMontantDeclare() {
		return this.montantDeclare;
	}

	public void setMontantDeclare(Double montantDeclare) {
		this.montantDeclare = montantDeclare;
	}

	@Column(name = "bureau", length = 200)
	public String getBureau() {
		return this.bureau;
	}

	public void setBureau(String bureau) {
		this.bureau = bureau;
	}

	@Column(name = "regime", length = 200)
	public String getRegime() {
		return this.regime;
	}

	public void setRegime(String regime) {
		this.regime = regime;
	}

	@Column(name = "numero_declaration")
	public Integer getNumeroDeclaration() {
		return this.numeroDeclaration;
	}

	public void setNumeroDeclaration(Integer numeroDeclaration) {
		this.numeroDeclaration = numeroDeclaration;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_declaration", length = 13)
	public Date getDateDeclaration() {
		return this.dateDeclaration;
	}

	public void setDateDeclaration(Date dateDeclaration) {
		this.dateDeclaration = dateDeclaration;
	}

	@Column(name = "montant_taxe", scale = 0)
	public Double getMontantTaxe() {
		return this.montantTaxe;
	}

	public void setMontantTaxe(Double montantTaxe) {
		this.montantTaxe = montantTaxe;
	}

	@Column(name = "observation")
	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

}
