package cm.beni.main.julia.model.schema.factures;
// Generated 2 ao�t 2020 02:36:36 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Facture generated by hbm2java
 */
@Entity
@Table(name = "facture", schema = "factures")
//@JsonIdentityInfo(generator=ObjectIdGenerators.UUIDGenerator.class, property="@facture", scope = Facture.class, resolver = ObjectIdResolver.class)
public class Facture implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String identify;
	private String dossier;
	private String referenceMovement;
	private String referenceBalance;
	private String description;
	private String reference4;
	private String reference5;
	private Double poids;
	private String referenceDeclaration;
	private String referenceCon;
	private Set<RubriquesFacture> rubriquesFactures = new HashSet<RubriquesFacture>(0);

	public Facture() {
	}

	public Facture(String identify, String dossier) {
		this.identify = identify;
		this.dossier = dossier;
	}

	public Facture(String identify, String dossier, String referenceMovement, String referenceBalance,
			String description, String reference4, String reference5, Double poids, String referenceDeclaration,
			String referenceCon, Set<RubriquesFacture> rubriquesFactures) {
		this.identify = identify;
		this.dossier = dossier;
		this.referenceMovement = referenceMovement;
		this.referenceBalance = referenceBalance;
		this.description = description;
		this.reference4 = reference4;
		this.reference5 = reference5;
		this.poids = poids;
		this.referenceDeclaration = referenceDeclaration;
		this.referenceCon = referenceCon;
		this.rubriquesFactures = rubriquesFactures;
	}

	@Id

	@Column(name = "identify", unique = true, nullable = false, length = 64)
	public String getIdentify() {
		return this.identify;
	}

	public void setIdentify(String identify) {
		this.identify = identify;
	}

	@Column(name = "dossier", nullable = false, length = 64)
	public String getDossier() {
		return this.dossier;
	}

	public void setDossier(String dossier) {
		this.dossier = dossier;
	}

	@Column(name = "reference_movement", length = 200)
	public String getReferenceMovement() {
		return this.referenceMovement;
	}

	public void setReferenceMovement(String referenceMovement) {
		this.referenceMovement = referenceMovement;
	}

	@Column(name = "reference_balance", length = 200)
	public String getReferenceBalance() {
		return this.referenceBalance;
	}

	public void setReferenceBalance(String referenceBalance) {
		this.referenceBalance = referenceBalance;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "reference_4", length = 200)
	public String getReference4() {
		return this.reference4;
	}

	public void setReference4(String reference4) {
		this.reference4 = reference4;
	}

	@Column(name = "reference_5", length = 200)
	public String getReference5() {
		return this.reference5;
	}

	public void setReference5(String reference5) {
		this.reference5 = reference5;
	}

	@Column(name = "poids", precision = 17, scale = 17)
	public Double getPoids() {
		return this.poids;
	}

	public void setPoids(Double poids) {
		this.poids = poids;
	}

	@Column(name = "reference_declaration", length = 200)
	public String getReferenceDeclaration() {
		return this.referenceDeclaration;
	}

	public void setReferenceDeclaration(String referenceDeclaration) {
		this.referenceDeclaration = referenceDeclaration;
	}

	@Column(name = "reference_con", length = 200)
	public String getReferenceCon() {
		return this.referenceCon;
	}

	public void setReferenceCon(String referenceCon) {
		this.referenceCon = referenceCon;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "facture")
	public Set<RubriquesFacture> getRubriquesFactures() {
		return this.rubriquesFactures;
	}

	public void setRubriquesFactures(Set<RubriquesFacture> rubriquesFactures) {
		this.rubriquesFactures = rubriquesFactures;
	}

}
