package cm.beni.main.julia.model.schema.factures;
// Generated 2 ao�t 2020 02:36:36 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.voodoodyne.jackson.jsog.JSOGGenerator;

import cm.beni.main.julia.dao.controller.ObjectIdResolver;
import cm.beni.main.julia.model.schema.dossiers.Dossier;

/**
 * Facture generated by hbm2java
 */
@Entity
@Table(name = "facture", schema = "factures")
//@JsonIdentityInfo(generator=ObjectIdGenerators.UUIDGenerator.class, property="@facture", scope = Facture.class, resolver = ObjectIdResolver.class)
@JsonIdentityInfo(generator=JSOGGenerator.class, resolver = ObjectIdResolver.class)
public class Facture implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String identify;
	private String numeroFacture;
	private Date dateMiseEnPlace;
	private String numeroProfessionnel;
	private Dossier dossier;
	private String referenceMovement;
	private String referenceBalance;
	private String description;
	private String[] reference;
	private String referenceDeclaration;
	private String numeroDeclaration;
	private String valeurDeclaration;
	private Double poids;
	private String referencePoids;
	private String referenceCon;
	private Set<RubriquesFacture> rubriquesFactures = new HashSet<RubriquesFacture>(0);

	public Facture() {
	}

	public Facture(String identify, Dossier dossier) {
		this.identify = identify;
		this.dossier = dossier;
	}

	public Facture(String identify, String numeroFacture, Date dateMiseEnPlace, String numeroProfessionnel,
			Dossier dossier, String referenceMovement, String referenceBalance, String description, String[] reference,
			String referenceDeclaration, String numeroDeclaration, String valeurDeclaration, Double poids,
			String referencePoids, String referenceCon, Set<RubriquesFacture> rubriquesFactures) {
		this.identify = identify;
		this.numeroFacture = numeroFacture;
		this.dateMiseEnPlace = dateMiseEnPlace;
		this.numeroProfessionnel = numeroProfessionnel;
		this.dossier = dossier;
		this.referenceMovement = referenceMovement;
		this.referenceBalance = referenceBalance;
		this.description = description;
		this.reference = reference;
		this.referenceDeclaration = referenceDeclaration;
		this.numeroDeclaration = numeroDeclaration;
		this.valeurDeclaration = valeurDeclaration;
		this.poids = poids;
		this.referencePoids = referencePoids;
		this.referenceCon = referenceCon;
		this.rubriquesFactures = rubriquesFactures;
	}

	@Id

	@Column(name = "identify", unique = true, nullable = false, length = 64)
	public String getIdentify() {
		return this.identify;
	}

	public void setIdentify(String identify) {
		this.identify = identify;
	}

	@Column(name = "numero_facture", unique = true, nullable = false, length = 100)
	public String getNumeroFacture() {
		return numeroFacture;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_mise_en_place", nullable = false, length = 13)
	public Date getDateMiseEnPlace() {
		return dateMiseEnPlace;
	}
	
	@Column(name = "numero_professionnel", unique = true, nullable = false, length = 100)
	public String getNumeroProfessionnel() {
		return numeroProfessionnel;
	}

	public void setNumeroProfessionnel(String numeroProfessionnel) {
		this.numeroProfessionnel = numeroProfessionnel;
	}

	public void setDateMiseEnPlace(Date dateMiseEnPlace) {
		this.dateMiseEnPlace = dateMiseEnPlace;
	}

	public void setNumeroFacture(String numeroFacture) {
		this.numeroFacture = numeroFacture;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dossier", nullable = false)
	public Dossier getDossier() {
		return this.dossier;
	}

	public void setDossier(Dossier dossier) {
		this.dossier = dossier;
	}

	@Column(name = "reference_movement", length = 200)
	public String getReferenceMovement() {
		return this.referenceMovement;
	}

	public void setReferenceMovement(String referenceMovement) {
		this.referenceMovement = referenceMovement;
	}

	@Column(name = "reference_balance", length = 200)
	public String getReferenceBalance() {
		return this.referenceBalance;
	}

	public void setReferenceBalance(String referenceBalance) {
		this.referenceBalance = referenceBalance;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "reference")
	public String[] getReference() {
		return this.reference;
	}

	public void setReference(String[] reference) {
		this.reference = reference;
	}

	@Column(name = "poids", precision = 17, scale = 17)
	public Double getPoids() {
		return this.poids;
	}

	public void setPoids(Double poids) {
		this.poids = poids;
	}

	@Column(name = "reference_poids", length = 200)
	public String getReferencePoids() {
		return referencePoids;
	}

	public void setReferencePoids(String referencePoids) {
		this.referencePoids = referencePoids;
	}

	@Column(name = "reference_declaration", length = 200)
	public String getReferenceDeclaration() {
		return this.referenceDeclaration;
	}

	public void setReferenceDeclaration(String referenceDeclaration) {
		this.referenceDeclaration = referenceDeclaration;
	}

	@Column(name = "numero_declaration", length = 200)
	public String getNumeroDeclaration() {
		return numeroDeclaration;
	}

	public void setNumeroDeclaration(String numeroDeclaration) {
		this.numeroDeclaration = numeroDeclaration;
	}

	@Column(name = "valeur_declaration", length = 200)
	public String getValeurDeclaration() {
		return valeurDeclaration;
	}

	public void setValeurDeclaration(String valeurDeclaration) {
		this.valeurDeclaration = valeurDeclaration;
	}

	@Column(name = "reference_con", length = 200)
	public String getReferenceCon() {
		return this.referenceCon;
	}

	public void setReferenceCon(String referenceCon) {
		this.referenceCon = referenceCon;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "facture")
	public Set<RubriquesFacture> getRubriquesFactures() {
		return this.rubriquesFactures;
	}

	public void setRubriquesFactures(Set<RubriquesFacture> rubriquesFactures) {
		this.rubriquesFactures = rubriquesFactures;
	}
}
