package cm.beni.main.julia.model.schema.factures;
// Generated 2 ao�t 2020 02:36:36 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.voodoodyne.jackson.jsog.JSOGGenerator;

import cm.beni.main.julia.dao.controller.ObjectIdResolver;

/**
 * Nature generated by hbm2java
 */
@Entity
@Table(name = "nature", schema = "factures", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
//@JsonIdentityInfo(generator=ObjectIdGenerators.UUIDGenerator.class, property="@nature", scope = Nature.class, resolver = ObjectIdResolver.class)
@JsonIdentityInfo(generator=JSOGGenerator.class, resolver = ObjectIdResolver.class)
public class Nature implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String identify;
	private String code;
	private String libelle;
	private double montant;
	private Set<Rubrique> rubriques = new HashSet<Rubrique>(0);

	public Nature() {
	}

	public Nature(String identify, String code, String libelle, double montant) {
		this.identify = identify;
		this.code = code;
		this.libelle = libelle;
		this.montant = montant;
	}

	public Nature(String identify, String code, String libelle, double montant, Set<Rubrique> rubriques) {
		this.identify = identify;
		this.code = code;
		this.libelle = libelle;
		this.montant = montant;
		this.rubriques = rubriques;
	}

	@Id

	@Column(name = "identify", unique = true, nullable = false, length = 64)
	public String getIdentify() {
		return this.identify;
	}

	public void setIdentify(String identify) {
		this.identify = identify;
	}

	@Column(name = "code", unique = true, nullable = false, length = 100)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "libelle", nullable = false, length = 200)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@Column(name = "montant", nullable = false, scale = 0)
	public double getMontant() {
		return this.montant;
	}

	public void setMontant(double montant) {
		this.montant = montant;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nature")
	public Set<Rubrique> getRubriques() {
		return this.rubriques;
	}

	public void setRubriques(Set<Rubrique> rubriques) {
		this.rubriques = rubriques;
	}

}
