package cm.beni.main.julia.model.schema.factures;
// Generated 2 ao�t 2020 02:36:36 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rubrique generated by hbm2java
 */
@Entity
@Table(name = "rubrique", schema = "factures")
//@JsonIdentityInfo(generator=ObjectIdGenerators.UUIDGenerator.class, property="@rubrique", scope = Rubrique.class, resolver = ObjectIdResolver.class)
public class Rubrique implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String identify;
	private Nature nature;
	private Operation operation;
	private String libelle;
	private String type;
	private Set<RubriquesFacture> rubriquesFactures = new HashSet<RubriquesFacture>(0);

	public Rubrique() {
	}

	public Rubrique(String identify, Nature nature, Operation operation, String libelle) {
		this.identify = identify;
		this.nature = nature;
		this.operation = operation;
		this.libelle = libelle;
	}

	public Rubrique(String identify, Nature nature, Operation operation, String libelle, String type,
			Set<RubriquesFacture> rubriquesFactures) {
		this.identify = identify;
		this.nature = nature;
		this.operation = operation;
		this.libelle = libelle;
		this.type = type;
		this.rubriquesFactures = rubriquesFactures;
	}

	@Id

	@Column(name = "identify", unique = true, nullable = false, length = 64)
	public String getIdentify() {
		return this.identify;
	}

	public void setIdentify(String identify) {
		this.identify = identify;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nature", nullable = false)
	public Nature getNature() {
		return this.nature;
	}

	public void setNature(Nature nature) {
		this.nature = nature;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "operation", nullable = false)
	public Operation getOperation() {
		return this.operation;
	}

	public void setOperation(Operation operation) {
		this.operation = operation;
	}

	@Column(name = "libelle", nullable = false, length = 200)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@Column(name = "type", length = 100)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rubrique")
	public Set<RubriquesFacture> getRubriquesFactures() {
		return this.rubriquesFactures;
	}

	public void setRubriquesFactures(Set<RubriquesFacture> rubriquesFactures) {
		this.rubriquesFactures = rubriquesFactures;
	}

}
