package cm.beni.main.julia.model.schema.security;
// Generated 2 ao�t 2020 02:43:52 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import cm.beni.main.julia.dao.controller.ObjectIdResolver;

/**
 * Level generated by hbm2java
 */
@Entity
@Table(name = "level", schema = "security", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
@JsonIdentityInfo(generator=ObjectIdGenerators.UUIDGenerator.class, property="@level", scope = Level.class, resolver = ObjectIdResolver.class)
public class Level implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String identify;
	private int order;
	private String code;
	private String libelle;
	private Set<User> users = new HashSet<User>(0);

	public Level() {
	}

	public Level(String identify, int order, String code, String libelle) {
		this.identify = identify;
		this.order = order;
		this.code = code;
		this.libelle = libelle;
	}

	public Level(String identify, int order, String code, String libelle, Set<User> users) {
		this.identify = identify;
		this.order = order;
		this.code = code;
		this.libelle = libelle;
		this.users = users;
	}

	@Id

	@Column(name = "identify", unique = true, nullable = false, length = 64)
	public String getIdentify() {
		return this.identify;
	}

	public void setIdentify(String identify) {
		this.identify = identify;
	}

	@Column(name = "order", nullable = false)
	public int getOrder() {
		return this.order;
	}

	public void setOrder(int order) {
		this.order = order;
	}

	@Column(name = "code", unique = true, nullable = false, length = 100)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "libelle", nullable = false, length = 200)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "level")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
