package cm.beni.main.julia.model.schema.security;
// Generated 2 ao�t 2020 02:43:52 by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import cm.beni.main.julia.dao.controller.ObjectIdResolver;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", schema = "security", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "user_name", "password" }),
		@UniqueConstraint(columnNames = { "first_name", "last_name" }), @UniqueConstraint(columnNames = "cni"),
		@UniqueConstraint(columnNames = { "user_name", "level" }) })
@JsonIdentityInfo(generator = ObjectIdGenerators.UUIDGenerator.class, property = "@user", scope = User.class, resolver = ObjectIdResolver.class)
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String identify;
	private Level level;
	private String userName;
	private String password;
	private String firstName;
	private String lastName;
	private Date birthday;
	private String birthLocation;
	private String cni;
	private String telephone;
	private String email;

	public User() {
	}

	public User(String identify, Level level, String userName, String password, String firstName, Date birthday,
			String cni) {
		this.identify = identify;
		this.level = level;
		this.userName = userName;
		this.password = password;
		this.firstName = firstName;
		this.birthday = birthday;
		this.cni = cni;
	}

	public User(String identify, Level level, String userName, String password, String firstName, String lastName,
			Date birthday, String birthLocation, String cni, String telephone, String email) {
		this.identify = identify;
		this.level = level;
		this.userName = userName;
		this.password = password;
		this.firstName = firstName;
		this.lastName = lastName;
		this.birthday = birthday;
		this.birthLocation = birthLocation;
		this.cni = cni;
		this.telephone = telephone;
		this.email = email;
	}

	@Id

	@Column(name = "identify", unique = true, nullable = false, length = 64)
	public String getIdentify() {
		return this.identify;
	}

	public void setIdentify(String identify) {
		this.identify = identify;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "level", nullable = false)
	public Level getLevel() {
		return this.level;
	}

	public void setLevel(Level level) {
		this.level = level;
	}

	@Column(name = "user_name", nullable = false, length = 200)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "password", nullable = false, length = 200)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "first_name", nullable = false, length = 200)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", length = 200)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthday", nullable = false, length = 13)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "birth_location", length = 200)
	public String getBirthLocation() {
		return this.birthLocation;
	}

	public void setBirthLocation(String birthLocation) {
		this.birthLocation = birthLocation;
	}

	@Column(name = "cni", unique = true, nullable = false, length = 100)
	public String getCni() {
		return this.cni;
	}

	public void setCni(String cni) {
		this.cni = cni;
	}

	@Column(name = "telephone")
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "email", length = 200)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
