package cm.beni.main.julia.model.schema.security;
// Generated 2 ao�t 2020 02:43:52 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import cm.beni.main.julia.dao.controller.ObjectIdResolver;

/**
 * Widget generated by hbm2java
 */
@Entity
@Table(name = "widget", schema = "security", uniqueConstraints = { @UniqueConstraint(columnNames = "order"),
		@UniqueConstraint(columnNames = "code"), @UniqueConstraint(columnNames = "position") })
@JsonIdentityInfo(generator=ObjectIdGenerators.UUIDGenerator.class, property="@widget", scope = Widget.class, resolver = ObjectIdResolver.class)
public class Widget implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String identify;
	private int order;
	private String code;
	private String label;
	private String position;
	private boolean disponible;

	public Widget() {
	}

	public Widget(String identify, int order, String code, String position, boolean disponible) {
		this.identify = identify;
		this.order = order;
		this.code = code;
		this.position = position;
		this.disponible = disponible;
	}

	public Widget(String identify, int order, String code, String label, String position, boolean disponible) {
		this.identify = identify;
		this.order = order;
		this.code = code;
		this.label = label;
		this.position = position;
		this.disponible = disponible;
	}

	@Id

	@Column(name = "identify", unique = true, nullable = false, length = 64)
	public String getIdentify() {
		return this.identify;
	}

	public void setIdentify(String identify) {
		this.identify = identify;
	}

	@Column(name = "order", unique = true, nullable = false)
	public int getOrder() {
		return this.order;
	}

	public void setOrder(int order) {
		this.order = order;
	}

	@Column(name = "code", unique = true, nullable = false, length = 100)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "label", length = 200)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "position", unique = true, nullable = false, length = 100)
	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	@Column(name = "disponible", nullable = false)
	public boolean isDisponible() {
		return this.disponible;
	}

	public void setDisponible(boolean disponible) {
		this.disponible = disponible;
	}

}
