package cm.beni.main.julia.model.schema.depenses;
// Generated 2 ao�t 2020 02:33:38 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.voodoodyne.jackson.jsog.JSOGGenerator;

import cm.beni.main.julia.dao.controller.ObjectIdResolver;

/**
 * Depense generated by hbm2java
 */
@Entity
@Table(name = "depense", schema = "depenses", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
//@JsonIdentityInfo(generator=ObjectIdGenerators.UUIDGenerator.class, property="@depense", scope = Depense.class, resolver = ObjectIdResolver.class)
@JsonIdentityInfo(generator=JSOGGenerator.class, resolver = ObjectIdResolver.class)
public class Depense implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String identify;
	private String code;
	private String libelle;
	private Set<DossierDepenses> dossierDepenseses = new HashSet<DossierDepenses>(0);

	public Depense() {
	}

	public Depense(String identify, String code, String libelle) {
		this.identify = identify;
		this.code = code;
		this.libelle = libelle;
	}

	public Depense(String identify, String code, String libelle, Set<DossierDepenses> dossierDepenseses) {
		this.identify = identify;
		this.code = code;
		this.libelle = libelle;
		this.dossierDepenseses = dossierDepenseses;
	}

	@Id

	@Column(name = "identify", unique = true, nullable = false, length = 64)
	public String getIdentify() {
		return this.identify;
	}

	public void setIdentify(String identify) {
		this.identify = identify;
	}

	@Column(name = "code", unique = true, nullable = false, length = 100)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "libelle", nullable = false, length = 200)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "depense")
	public Set<DossierDepenses> getDossierDepenseses() {
		return this.dossierDepenseses;
	}

	public void setDossierDepenseses(Set<DossierDepenses> dossierDepenseses) {
		this.dossierDepenseses = dossierDepenseses;
	}

}
